// Generated by CoffeeScript 1.6.3
/*
// ==UserScript==
// @name SpectaBot
// @description Auto-spectates TagPro games for scripting 
// @version 0.0.1
// @include *://tagpro-*.koalabeast.com*
// ==/UserScript==
*/


(function() {
  alert("Loaded script");

}).call(this);
